spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:54320/stockx_true_to_size
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,metrics,health"
    health:
      show-details: always
  server:
    port: 8079
