spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:54320/stockx_true_to_size
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver